# Generated by Django 4.0.1 on 2022-01-20 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flame',
            field=models.ManyToManyField(blank=True, related_name='flame', to=settings.AUTH_USER_MODEL),
        ),
    ]
