# Generated by Django 4.0.1 on 2022-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='bio',
            field=models.TextField(blank=True, default='student', null=True),
        ),
    ]
