# Generated by Django 4.0.1 on 2022-01-08 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_createaccount_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('current_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('team_members', models.CharField(blank=True, max_length=20, null=True)),
                ('project_img', models.ImageField(blank=True, null=True, upload_to='project_img/')),
                ('project_type', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('project_file', models.FileField(blank=True, null=True, upload_to='project-files/')),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_time'],
            },
        ),
    ]
