# Generated by Django 4.0.1 on 2022-01-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_project_flame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='fb',
            field=models.URLField(blank=True, default='www.facebook.com'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='github',
            field=models.URLField(blank=True, default='github.com'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='insta',
            field=models.URLField(blank=True, default='instagram.com'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='linkedin',
            field=models.URLField(blank=True, default='linkedin.com'),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='website',
            field=models.URLField(blank=True, default='myportfoilo.com'),
        ),
    ]
