# Generated by Django 4.0.1 on 2022-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccount',
            name='fb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='insta',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createaccount',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
