# Generated by Django 4.0.1 on 2022-01-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_createaccount_fb_createaccount_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='fb',
            field=models.URLField(blank=True, default='https://www.facebook.com/', null=True),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='github',
            field=models.URLField(blank=True, default='https://github.com/', null=True),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='insta',
            field=models.URLField(blank=True, default='https://instagram.com/', null=True),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='linkedin',
            field=models.URLField(blank=True, default='https://linkedin.com/', null=True),
        ),
        migrations.AlterField(
            model_name='createaccount',
            name='website',
            field=models.URLField(blank=True, default='myportfoilo.com', null=True),
        ),
    ]
