# Generated by Django 4.0.1 on 2022-01-17 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_createaccount_fb_alter_createaccount_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='comment',
            field=models.ManyToManyField(null=True, related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
