# Generated by Django 4.0.1 on 2022-01-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[(0, 'Not Selected'), (1, 'Python Project'), (2, 'Mern Project'), (3, 'React Project'), (4, 'Deeplearning Project'), (5, 'Machine Learning Project'), (6, 'DataScience Project'), (7, 'Javascript Project'), (8, 'Css Project'), (9, 'Django Project'), (10, 'Angular Project')], default=0, max_length=2),
        ),
    ]
