# Generated by Django 4.0.1 on 2022-01-17 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_project_comment_project_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.ManyToManyField(related_name='comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
