# Generated by Django 4.0.1 on 2022-01-24 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(default=None, related_name='project_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
