# Generated by Django 4.0.1 on 2022-01-24 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_project_project_type_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flame',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='project_flame', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='project_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
