# Generated by Django 4.0.1 on 2022-01-24 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_project_flame_alter_project_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='flame',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_flame', to=settings.AUTH_USER_MODEL),
        ),
    ]
