# Generated by Django 4.0.1 on 2022-01-25 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_project_flame'),
    ]

    operations = [
        migrations.AddField(
            model_name='createaccount',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, default=None, related_name='project_team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
